name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 自动运行
  workflow_dispatch: # 手动触发执行

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 配置 Git 用户名和电子邮件
      - name: Configure Git Identity
        run: |
          git config --global user.name "Reviewa"
          git config --global user.email "7452323@gmail.com"

      # 检出复刻仓库代码
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 添加上游仓库为远程仓库
      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/findmover/wxread.git
          git fetch upstream
          git checkout main # 如果默认分支是 master，请改为 git checkout master
          git merge upstream/main --allow-unrelated-histories # 如果默认分支是 master，请改为 upstream/master

      # 推送更新到复刻仓库
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main --force # 如果默认分支是 master，请改为 origin/master
